import Framer from "./framer_components/Framer.js";
import { FramerComponent } from "./framer_components/Framer.js";
export default class GetStarted extends FramerComponent {
    init() {
        this.append(Framer.createElement("div", { className: "container" },
            Framer.createElement("div", { className: "section-center" },
                Framer.createElement("article", null,
                    Framer.createElement("h1", null, "Basics"),
                    Framer.createElement("p", null, "Alright so the rules here are pretty simple. You have an application (FramerApp) that everything is rendered in and components (FramerComponents) that act as HTML elements but more manipulatable. FramerComponents extend the HTMLElement class and therefore inherit all those cool functions but you are also able to write your own and get them to work how you want with custom HTML Framer Components. Everything here is intended to be written in TypeScript (except for obviously the HTML and CSS) and everything works as modules - much like the many other web frameworks out there. Speaking of many other frameworks, there is support for JSX - hooray! \uD83C\uDF89 - so it is super easy to write your HTML inline with your typescript code just like you would with a framework like React."))),
            Framer.createElement("hr", { className: "varient" }),
            Framer.createElement("div", { className: "section-left-focus" },
                Framer.createElement("article", null,
                    Framer.createElement("h1", null, "Setup"),
                    Framer.createElement("p", null,
                        "First and foremost, make sure you have the ",
                        Framer.createElement("a", { target: "_blank", href: "https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html" }, "TypeScript"),
                        " Compiler installed on your development machine. If you have npm installed you can just run the command ",
                        Framer.createElement("code", null, "npm install -g typescript"),
                        ". If you have ",
                        Framer.createElement("a", { target: "_blank", href: "https://code.visualstudio.com/download" }, "VSCode"),
                        " the remainder of the setup has been done for you, just download the example project and get started. In the example project you will find I have predefined two helpful VSCode snippets, ",
                        Framer.createElement("code", null, "cfa"),
                        " and ",
                        Framer.createElement("code", null, "cfc"),
                        ". ",
                        Framer.createElement("code", null, "cfa"),
                        " creates a template for a Framer Application and ",
                        Framer.createElement("code", null, "cfc"),
                        " creates a template for a Framer Component. To start developing you can use the ",
                        Framer.createElement("code", null, "ctrl + shift + b"),
                        " (Run Build Task) keyboard shortcut and choose the predefined ",
                        Framer.createElement("code", null, "tsc:watch - tsconfig.json"),
                        " task, which will basically start transpiling everything into JavaScript in the background and if you use the watch task it will even re-transpile your code as you save your TypeScript files automatically - nice! \uD83D\uDC4D Also to enhance your development experience, I would recommend installing ",
                        Framer.createElement("a", { target: "_blank", href: "https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer" }, "Live Server"),
                        " from the VSCode market place, after installing Live Server open up the index.html file for the project and right click anywhere ont the code, choose open with Live Server. This will serve your project and it automatically reloads the in-development webpage whenever it detects a change in code.")),
                Framer.createElement("img", { className: "img outsider-logo", src: "./assets/vscode.png" })),
            Framer.createElement("hr", { className: "varient" }),
            Framer.createElement("div", { className: "section-center" },
                Framer.createElement("article", null,
                    Framer.createElement("h1", null, "More Information"),
                    Framer.createElement("p", null, "As of right now this is all in early stages of development, that said there will likely be more helpful information added to this page soon. If you're in need of more information for now take a look at the example project and try to understand what's going on there. Also be sure to look through the provided documentation. Finally make sure to check in on these resources once in a while because they will be added to in the near future!"))),
            Framer.createElement("hr", { className: "varient" }),
            Framer.createElement("div", { className: "section-center" },
                Framer.createElement("article", null,
                    Framer.createElement("h1", null, "Learning Resources"),
                    Framer.createElement("p", null,
                        "Below you can find links to helpful resources for learning different web-development skills.",
                        Framer.createElement("ul", null,
                            Framer.createElement("li", null,
                                "W3Schools: ",
                                Framer.createElement("a", { target: "_blank", href: "https://www.w3schools.com/" }, "Tons of helpful general tutorials")),
                            Framer.createElement("li", null,
                                "MDN web docs: ",
                                Framer.createElement("a", { target: "_blank", href: "https://developer.mozilla.org/en-US/" }, "Another resource with tons of great tutorials and information")),
                            Framer.createElement("li", null,
                                "Codecademy: ",
                                Framer.createElement("a", { target: "_blank", href: "https://www.codecademy.com/learn/learn-html" }, "Introduction to HTML")),
                            Framer.createElement("li", null,
                                "Codecademy: ",
                                Framer.createElement("a", { target: "_blank", href: "https://www.codecademy.com/learn/learn-css" }, "Learn CSS")),
                            Framer.createElement("li", null,
                                "TypeScript: ",
                                Framer.createElement("a", { target: "_blank", href: "https://www.typescriptlang.org/docs/home.html" }, "Documentation and Resources")),
                            Framer.createElement("li", null,
                                "ReactJS: ",
                                Framer.createElement("a", { target: "_blank", href: "https://reactjs.org/docs/introducing-jsx.html" }, "Introducing JSX"),
                                " (just ignore the information about React unless you want to learn that instead)"),
                            Framer.createElement("li", null,
                                "GitHub: ",
                                Framer.createElement("a", { target: "_blank", href: "https://try.github.io/" }, "Resources to learn Git"))))))));
    }
}
